[features]
seeds = false
skip-lint = false

[programs.localnet]
solquad = "2pQQCZvX52S3paQYg3JLfghQCE7hates7Ma62mL6GKMS"

[programs.devnet]
solquad = "2pQQCZvX52S3paQYg3JLfghQCE7hates7Ma62mL6GKMS"

[registry]
url = "https://api.apr.dev"

# [provider.localnet]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
